FROM pytorch/pytorch:latest

COPY ./main.py /main.py

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1


# SYSTEM
RUN apt-get update --yes --quiet && DEBIAN_FRONTEND=noninteractive apt-get install --yes --quiet --no-install-recommends \
    software-properties-common \
    build-essential apt-utils \
    pkg-config libicu-dev \
    gpg-agent \
    git-all \ 
    wget curl vim git ca-certificates kmod sudo git bzip2 libx11-6 screen \
    && rm -rf /var/lib/apt/lists/*


RUN python -m pip install --upgrade pip setuptools

# python requirements
COPY ./requirements.txt /requirements.txt
RUN pip install -r /requirements.txt

COPY ./entrypoint.sh /
RUN chmod +x /entrypoint.sh

# bash script on entry
ENTRYPOINT ["/entrypoint.sh"]
