FROM nvidia/cuda:12.2.2-devel-ubuntu22.04

ENV PYTHONUNBUFFERED 1
ENV PYTHONDONTWRITEBYTECODE 1


# SYSTEM
RUN apt-get update --yes --quiet && DEBIAN_FRONTEND=noninteractive apt-get install --yes --quiet --no-install-recommends \
    software-properties-common \
    build-essential apt-utils \
    pkg-config libicu-dev \
    wget curl vim git ca-certificates kmod sudo git bzip2 libx11-6 screen \
    && rm -rf /var/lib/apt/lists/*


# PYTHON 3.10
RUN add-apt-repository --yes ppa:deadsnakes/ppa && apt-get update --yes --quiet
RUN DEBIAN_FRONTEND=noninteractive apt-get install --yes --quiet --no-install-recommends \
    python3.10 \
    python3.10-dev \
    python3.10-distutils \
    python3.10-lib2to3 \
    python3.10-gdbm \
    python3.10-tk

RUN curl -sS https://bootstrap.pypa.io/get-pip.py | python3.10

RUN update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 999 \
    && update-alternatives --config python3 && ln -s /usr/bin/python3 /usr/bin/python

ENV NVIDIA_VISIBLE_DEVICES all
ENV NVIDIA_DRIVER_CAPABILITIES compute,utility
ENV TORCH_CUDA_ARCH_LIST="compute capability"
LABEL com.nvidia.volumes.needed="nvidia_driver"

RUN python3.10 -m pip install --upgrade pip setuptools


COPY ./requirements.txt /requirements.txt

RUN pip3.10 install torch torchvision torchaudio

RUN pip3.10 install -r requirements.txt

RUN pip3.10 install jupyter jupyterlab

COPY ./entrypoint.sh /
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]